---
# tasks file for base_ami

# Yum update
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

#Disable SELINUX
- name: Disable SELINUX
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disable'

# Create 4G Swap file
- name: Write Swapfile
  command: dd if=/dev/zero of=/swapfile bs=1M count=4048
  
- name: Set swapfile permissions
  file: path=/swapfile mode=600

- name: Create swapfile
  command: mkswap /swapfile

- name: Enable swapfile
  command: swapon /swapfile 

- name: add swapfile to /etc/fstab'
  lineinfile: 
    path: /etc/fstab
    line: "/swapfile   none   swap   sw   0   0" 
    state: present


  # Create Directories
- file:
    path: /opt/prometheus_node_exporter/
 
#Download Node Exporter
- name: Download Prometheus Node Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v0.17.0/node_exporter-0.17.0.linux-amd64.tar.gz
    dest: /tmp/

#Unarchive Node Exporter
- name: Unarchive node exporter
  unarchive:  
    src: /tmp/node_exporter-0.17.0.linux-amd64.tar.gz
    dest: /opt/prometheus_node_exporter/

#Start Prometheus Node Exporter
- name: Start Prometheus Node Exporter
  shell: /opt/prometheus_node_exporter/node_exporter-0.17.0.linux-amd64/node_exporter &

#Install Filebeats for log shipping
- name: Install filebeats
  yum:
    name: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.5.4-x86_64.rpm
    state: present

